FUNCTION CHARCON(CHR1, CHR2, CHR3, CHR4, CHR5)
	PUBLIC C1,C2,C3,C4
	CHR5=""
	
	IF EMPTY(CHR1)
		CHR1=""
		C1=0
	ELSE
		C1=1
	ENDIF
	IF CHECKCHR(CHR1) = .T.
		CHR1 = IIF(C1=1, CHR1, ALLTRIM(CHR1))
	ELSE
		CHR1 = IIF(C1=1, CHR1+CHR(10), ALLTRIM(CHR1))
	ENDIF
	
	IF EMPTY(CHR2)
		CHR2=""
		C2=0
	ELSE
		C2=1
	ENDIF
	IF CHECKCHR(CHR2) = .T.
		CHR2 = IIF(C2=1, CHR2, ALLTRIM(CHR2))
	ELSE
		CHR2 = IIF(C2=1, CHR2+CHR(10), ALLTRIM(CHR2))
	ENDIF
	
	IF EMPTY(CHR3)
		CHR3=""
		C3=0
	ELSE
		C3=1
	ENDIF
	IF CHECKCHR(CHR3) = .T.
		CHR3 = IIF(C3=1, CHR3, ALLTRIM(CHR3))
	else
		CHR3 = IIF(C3=1, CHR3+CHR(10), ALLTRIM(CHR3))
	ENDIF
	
	
	IF EMPTY(CHR4)
		CHR4=""
		C4=0
	ELSE
		C4=1
	ENDIF
	IF CHECKCHR(CHR4) = .T.
		CHR4 = IIF(C4=1, CHR4, ALLTRIM(CHR4))
	ELSE
		CHR4 = IIF(C4=1, CHR4+CHR(10), ALLTRIM(CHR4))
	ENDIF
	
	CHR5 = CHR1+CHR2+CHR3+CHR4

	RETURN CHR5

FUNCTION CHECKCHR(X)	
	IF  SUBSTR(X,LEN(X)) = CHR(10)
		RETURN .T.
	ELSE
		RETURN .F.
	ENDIF
	