FUNCTION NUMVAL(TEMP_STR)

NUM_STR=""
REF_POS=AT(",", ALLTRIM(TEMP_STR))
DO WHILE REF_POS > 0
       NUM_STR=NUM_STR+SUBSTR(ALLTRIM(TEMP_STR),1,REF_POS-1)
       TEMP_STR=SUBSTR(ALLTRIM(TEMP_STR),REF_POS+1,LEN(ALLTRIM(TEMP_STR))-REF_POS)
       REF_POS=AT(",", ALLTRIM(TEMP_STR)) 
ENDDO 
NUM_STR=NUM_STR+TEMP_STR 
REF_POS=AT(".", ALLTRIM(NUM_STR))
IF REF_POS = 0
    NUM_VAL=VAL(NUM_STR)
ELSE
    NUM_VAL=VAL(SUBSTR(ALLTRIM(NUM_STR), 1, REF_POS-1))
    DEC_VALUE=SUBSTR(ALLTRIM(NUM_STR),REF_POS+1,LEN(ALLTRIM(NUM_STR))-REF_POS)
    NUM_VAL=NUM_VAL + VAL(DEC_VALUE) / (10**LEN(ALLTRIM(DEC_VALUE)))
ENDIF    
        

RETURN (NUM_VAL)
                     
