
CREATE TABLE C:\WCOMMPAY FREE;
	(YEAR N(4), MONTH N(2), SALESMAN C(2), SALESNAME C(30),INVOICE C(10), CUST_CODE C(10),;
	 CONFIRM C(8), ITEM_NO C(8), GROSS_AMT N(9,2), NET_AMT N(9,2), COMM N(7,2),;
	 COMM_RATE N(5,2) , po_no c(20))