FUNCTION UPORDENQ(U_OE_NO)
PUBLIC W_PACKING
* U_OE_NO = "HT-OC/112/00"
  
SELECT OE_NO,ITEM_NO,  QTY, CTN, VENDOR_NO,;
	PRICE, COST, DEL_DATE, CUST_NO, REMARK, CUR_CODE,;
		PACK_PC_1,PACK_PC_2,PACK_PC_3,PACK_PC_4;
		FROM MOE WHERE OE_NO = U_OE_NO ORDER BY ITEM_NO;
			INTO CURSOR TEMP_MOE
			
IF USED("WPORDENQ")
	SELECT WPORDENQ
	ZAP
ELSE
	USE  WPORDENQ IN 0 EXCLUSIVE
	ZAP
ENDIF

SELECT TEMP_MOE
DO WHILE !EOF()
	SELECT WPORDENQ
	APPEND BLANK
	
	REPLACE WPORDENQ.OE_NO WITH TEMP_MOE.OE_NO
	REPLACE WPORDENQ.ITEM_NO WITH TEMP_MOE.ITEM_NO
	REPLACE WPORDENQ.QTY WITH TEMP_MOE.QTY
	REPLACE WPORDENQ.CTN WITH TEMP_MOE.CTN
	REPLACE WPORDENQ.VENDOR_NO WITH TEMP_MOE.VENDOR_NO
	REPLACE WPORDENQ.PRICE WITH TEMP_MOE.PRICE
	REPLACE WPORDENQ.COST WITH TEMP_MOE.COST
	REPLACE WPORDENQ.DEL_DATE WITH TEMP_MOE.DEL_DATE
	REPLACE WPORDENQ.CUST_NO WITH TEMP_MOE.CUST_NO
	REPLACE WPORDENQ.CUR_CODE WITH TEMP_MOE.CUR_CODE
	REPLACE WPORDENQ.REMARK WITH TEMP_MOE.REMARK
	W_PACKING = ALLTRIM(STR(TEMP_MOE.PACK_PC_2))+" / "+ALLTRIM(STR(TEMP_MOE.PACK_PC_3))
*	MESSAGEBOX(W_PACKING)
	REPLACE WPORDENQ.PACKING WITH W_PACKING

	SELECT TEMP_MOE
	SKIP
ENDDO


SELECT TEMP_MOE
USE

FUNCTION FPACKING(W_PACK_1,W_PACK_2,W_PACK_3,W_PACK_4)