close table all
IF USED("BAITIN!MCUSTOM")
	SELECT MCUSTOM
ELSE 
	USE BAITIN!MCUSTOM IN 0
ENDIF
ZAP
public temp_var
temp_var = w_path +"\cus"
IF USED("CUS")
	SELECT CUS
ELSE 
	USE &temp_var IN 0
ENDIF

select * from cus where C_cname = "CUSTOMER" or c_cname = "TRADING" order by c_no;
INTO CURSOR CUS_CUSTOR

SELECT CUS_CUSTOR
DO WHILE !EOF()
	
	SELECT MCUSTOM 
	APPEND BLANK

	REPLACE MCUSTOM.CUST_NO  WITH CUS_CUSTOR.C_NO
	REPLACE MCUSTOM.DATE 	WITH CUS_CUSTOR.DATE
	REPLACE MCUSTOM.ENAME 	WITH CUS_CUSTOR.C_ENAME
	REPLACE MCUSTOM.SNAME	WITH CUS_CUSTOR.C_SHORT
	REPLACE MCUSTOM.ADDR1 	WITH CUS_CUSTOR.C_ADD1
	REPLACE MCUSTOM.ADDR2	WITH CUS_CUSTOR.C_ADD2
	REPLACE MCUSTOM.ADDR3	WITH CUS_CUSTOR.C_ADD3
	REPLACE MCUSTOM.ADDR4 	WITH CUS_CUSTOR.C_ADD4
	REPLACE MCUSTOM.CONT_NAME WITH CUS_CUSTOR.C_NAME
	REPLACE MCUSTOM.TEL 		WITH CUS_CUSTOR.C_TEL
	REPLACE MCUSTOM.TEL2 		WITH CUS_CUSTOR.C_TEL2
	REPLACE MCUSTOM.FAX 		WITH CUS_CUSTOR.C_FAX
	REPLACE MCUSTOM.FAX2 		WITH CUS_CUSTOR.C_FAX2
	REPLACE MCUSTOM.TERM 	WITH CUS_CUSTOR.C_TERM
	REPLACE MCUSTOM.PER_A 	WITH CUS_CUSTOR.PER_A
	REPLACE MCUSTOM.PER_B 	WITH CUS_CUSTOR.PER_B
	REPLACE MCUSTOM.PER_C 	WITH CUS_CUSTOR.PER_C
	REPLACE MCUSTOM.PER_D 	WITH CUS_CUSTOR.PER_D
	REPLACE MCUSTOM.PER_E 	WITH CUS_CUSTOR.PER_E
	
	temp_var = CHARCON(charcon(CUS_CUSTOR.M11,CUS_CUSTOR.M12,CUS_CUSTOR.M13,CUS_CUSTOR.M14),;
		charcon(CUS_CUSTOR.M15,CUS_CUSTOR.M16,CUS_CUSTOR.M17,CUS_CUSTOR.M18),;
			charcon(CUS_CUSTOR.M19,CUS_CUSTOR.M20,CUS_CUSTOR.M21,CUS_CUSTOR.M22),;
				charcon(CUS_CUSTOR.M23,CUS_CUSTOR.M24,CUS_CUSTOR.M25,CUS_CUSTOR.M26))

	REPLACE MCUSTOM.SHIPMARK WITH TEMP_VAR
	
	SELECT CUS_CUSTOR
	SKIP
ENDDO