CLOSE TABLE ALL
PRIVATE I

IF USED("BAITIN!MOE")
	SELECT MOE
	zap
ELSE
	USE BAITIN!MOE IN 2 EXCLUSIVE
	SELECT MOE
	zap
ENDIF
temp = w_path+"\"+"OE1"
IF USED("BAITIN!OE1")
	SELECT OE1
ELSE
	USE &temp IN 1 EXCLUSIVE
ENDIF

SELECT OE1
*locate for oe_no ="120/00"
DO WHILE !EOF()
	SELECT MOE
	APPEND BLANK
	REPLACE MOE.OE_NO 		WITH OE1.OE_NO
	REPLACE MOE.DATE 			WITH OE1.DATE
	REPLACE MOE.CUST_NO 		WITH OE1.C_NO
	REPLACE MOE.ITEM_NO 		WITH OE1.I_NO
	REPLACE MOE.QTY			WITH OE1.QTY
	REPLACE MOE.UNIT 			WITH OE1.UNIT
	REPLACE MOE.CTN			WITH val(alltrim(OE1.CTNS))
	REPLACE MOE.PRICE			WITH OE1.PRICE
	REPLACE MOE.CUR_CODE		WITH OE1.C_CUR
	REPLACE MOE.COST			WITH OE1.COST
	REPLACE MOE.ITEM_DESC 	WITH CHARCON(OE1.SECT1, OE1.SECT2)
	REPLACE MOE.DEL_DATE 		WITH OE1.DLY_DATE
	REPLACE MOE.CUBE			WITH OE1.CUBE
	REPLACE MOE.MEAS			WITH OE1.MEAS
	REPLACE MOE.PACK_PC_1 	WITH SUBNUM(OE1.PACK1)
	REPLACE MOE.PACK_PC_2 	WITH SUBNUM(OE1.PACK2)
	REPLACE MOE.PACK_PC_3 	WITH SUBNUM(OE1.PACK3)
	REPLACE MOE.PACK_PC_4 	WITH SUBNUM(OE1.PACK4)
	REPLACE MOE.PACK_DESP 	WITH CHARCON(oe1.PACK1,oe1.PACK2,oe1.PACK3,oe1.PACK4)
	REPLACE MOE.LC_DATE 		WITH OE1.LC_DATE
*	REPLACE MOE.VESSEL_DATE 	WITH 
	REPLACE MOE.PO_NO 		WITH OE1.PO_NO
	REPLACE MOE.OC_NO 		WITH OE1.OC_NO
	REPLACE MOE.VENDOR_NO 	WITH OE1.V_NO
	REPLACE MOE.REMARK 		WITH CHARCON(OE1.REM1,OE1.REM2,OE1.REM3)
	REPLACE MOE.status			with 1
	if at(alltrim(oe1.oe_no),"/") >0
		REPLACE MOE.comp_code	with "HT"
	else
		REPLACE MOE.comp_code	with "BAT"
	endif
	
	SELECT OE1
	SKIP
		
ENDDO

MESSAGEBOX("งนฆจ!")


