*UPDATE VENTOR*
CLOSE TABLE ALL
IF USED("BAITIN!MCUSTOM")
	SELECT MVENDOR
	
ELSE 
	USE BAITIN!MVENDOR IN 1
ENDIF
ZAP

IF USED("CUS")
	SELECT CUS
ELSE 
	USE CUS IN 2
ENDIF

select * from cus WHERE C_CNAME="VENDOR" or C_CNAME="MAKER" INTO CURSOR CUS_CUSTOR

SELECT CUS_CUSTOR
DO WHILE !EOF()
	
	SELECT MVENDOR 
	APPEND BLANK
	
	REPLACE MVENDOR.VENDOR_NO WITH CUS_CUSTOR.C_NO
	REPLACE MVENDOR.DATE 	WITH CUS_CUSTOR.DATE
	REPLACE MVENDOR.ENAME 	WITH CUS_CUSTOR.C_ENAME
	REPLACE MVENDOR.SNAME	WITH CUS_CUSTOR.C_SHORT
	REPLACE MVENDOR.ADDR1 	WITH CUS_CUSTOR.C_ADD1
	REPLACE MVENDOR.ADDR2	WITH CUS_CUSTOR.C_ADD2
	REPLACE MVENDOR.ADDR3	WITH CUS_CUSTOR.C_ADD3
	REPLACE MVENDOR.ADDR4 	WITH CUS_CUSTOR.C_ADD4
	REPLACE MVENDOR.CONT_NAME WITH CUS_CUSTOR.C_NAME
	REPLACE MVENDOR.TEL 		WITH CUS_CUSTOR.C_TEL
	REPLACE MVENDOR.TEL2 		WITH CUS_CUSTOR.C_TEL2
	REPLACE MVENDOR.FAX 		WITH CUS_CUSTOR.C_FAX
	REPLACE MVENDOR.FAX2 	WITH CUS_CUSTOR.C_FAX2
	IF CUS_CUSTOR.C_CNAME = "VENDOR"
		REPLACE MVENDOR.TYPE 		WITH 1
	ELSE 
		REPLACE MVENDOR.TYPE 		WITH 2
	ENDIF
	
	SELECT CUS_CUSTOR
	SKIP
	
ENDDO

clear all
