FUNCTION ZSPECPRICE(TEMP_ITEM_NO,TEMP_VENDOR_NO)

SELECT MSPECPRICE
SET ORDER TO IITEM_REF
SEEK TEMP_ITEM_NO + TEMP_VENDOR_NO
IF EOF()
    RETURN .F.
ELSE 
    RETURN .T.
ENDIF     

                     
